repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0  # Use the ref you want to point at
    hooks:
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-toml
    -   id: check-yaml
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: no-commit-to-branch
        args: ['--branch', 'main']

-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        args: [--config=pyproject.toml]

-   repo: https://github.com/hadialqattan/pycln
    rev: v1.3.3
    hooks:
    -   id: pycln
        args: [--config=pyproject.toml]

-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        files: "\\.(py)$"
        args: [--settings-path=pyproject.toml]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.960
    hooks:
    -   id: mypy

-   repo: https://github.com/commitizen-tools/commitizen
    rev: v2.27.1
    hooks:
    -   id: commitizen
        stages: [commit-msg]

-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.1.1
    hooks:
    -   id: conventional-pre-commit
